### ISSUE TITLE
expected dtype Byte but got dtype Bool

### ISSUE THREAD

**Issue by mengyunyun0824** [HLTCHKUST/PAML#19]
Hi！
An error occurs when I run MAML.py. Can you give me some advice? Thanks a lot!

**Issue summary**
Traceback (most recent call last):
  File "MAML.py", line 149, in <module>
    v_loss, v_ppl = do_evaluation(meta_net, val_iter)
  File "MAML.py", line 99, in do_evaluation
    loss, ppl, _ = model.train_one_batch(batch, train=False)
  File "C:\Users\lenovo\Desktop\PAML\PAML\model\transformer.py", line 329, in train_one_batch
    pre_logit, attn_dist = self.decoder(self.embedding(dec_batch_shift),encoder_outputs, (mask_src,mask_trg))
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\lenovo\Desktop\PAML\PAML\model\transformer.py", line 177, in forward
    dec_mask = torch.gt(mask_trg + self.mask[:, :mask_trg.size(-1), :mask_trg.size(-1)], 0)

**RuntimeError: expected device cuda:0 and dtype Byte but got device cuda:0 and dtype Bool**

**Comment by mengyunyun0824** [comment]
Is it because I am using torch==1.2.0 ?
